# Generated by Django 2.2.7 on 2019-11-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=500)),
                ('a_class', models.IntegerField()),
                ('a_company', models.CharField(max_length=500)),
                ('a_title', models.CharField(max_length=500)),
                ('a_field', models.CharField(max_length=500)),
                ('a_email', models.EmailField(max_length=254)),
                ('a_city', models.CharField(max_length=500)),
                ('a_country', models.CharField(max_length=500)),
            ],
        ),
    ]
