# Generated by Django 2.2.7 on 2019-11-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('alumnus', 'a_name', 'name')
    ]
